# Generated by Django 4.2.1 on 2023-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bear", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
