# Generated by Django 4.2.1 on 2023-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bear", "0002_log_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="image",
        ),
        migrations.AddField(
            model_name="log",
            name="image_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
