# Generated by Django 4.2.1 on 2023-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coala", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="time_falling_asleep",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="record",
            name="time_getting_up",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="record",
            name="time_going_bed",
            field=models.CharField(max_length=5),
        ),
    ]
