# Generated by Django 4.2.1 on 2023-09-03 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("coala", "0004_performance_registered_datetime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge", models.CharField(max_length=250)),
                ("evaluation", models.IntegerField(default=0)),
                (
                    "registered_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
